---
- name: launch an rds
  rds:
    command: create
    instance_name: "{{instance_name}}"
    db_engine: Postgres
    instance_type: "{{instance_type}}"
    username: postgres
    password: hackoregon
    license_model: postgresql-license
    dbname: postgres
    security_group: "{{security_group}}"
    size: 5
    region: "{{region}}"
    vpc_subnet_id: "{{vpc_subnet_id}}"
    keypair: "{{keypair}}"
    group: "{{group}}"
    assign_public_ip: "{{assign_public_ip}}"
    instance_tags: "{{instance_tags}}"
    source_dest_check: "{{source_dest_check}}"
    id: "{{id}}"
    wait: "{{wait}}"
  register: ec2_info

- debug: var=ec2_info

- debug: var=item
  with_items: ec2_info.instance_ids

- add_host: hostname={{item.public_ip}} groupname=tag_Name_{{group}}
  with_items: ec2_info.instances

- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{item.public_dns_name}}"
    port: 22
  with_items: ec2_info.instances
